name: Import term
description: Import term from a registered ontology into nfdi4pso
title: "[Import] "
labels: [term-add]
assignees: 
body:
 
  - type: input
    id: term
    attributes:
      label: Import term title
      description: Please enter the name of the term to be added 
      placeholder: "example term here"
    validations:
      required: true
