name: "Import term"
description: "Import term from a registered ontology into nfdi4pso"
title: "[Import] "
labels: [term-add]
body:
 
  - type: input
    id: term
    attributes:
      label: Import term title
      description: Please enter the name of the term to be added 
      placeholder: "example term here"
    validations:
      required: true
      
  - type: input
    id: Link and accession number
    attributes:
      label: Link and accession number
      description: Please enter the term accession number and URI
      placeholder: "EXAMPLE_00000111 (http://purl.obolibrary.org/exampleobo/EXAMPLE_00000111)"
    validations:
      required: true
      
     
