name: Add new term 
description: Suggest a new term to be added to the nfdi4pso ontology
title: "[NTR]"
labels: [add term]
assignees: ''
body:
  - type: input
    id: term
    attributes:
      label: New term name
      description: Please enter the name of the term to be added
      placeholder: "example term here"
    validations:
      required: true

  - type: textarea
    id: Definition
    attributes:
      label: Definition
      description: Please describe the term and provide a link to the definition source
    validations:
      required: true
      
      
  - type: textarea
    id: Synonyms
    attributes:
      label: Synonyms
      description: Please provide any synonyms for the new term
    validations:
      required: false
      
 - type: input
    id: Linked terms- Parent
    attributes:
      label: Parent term(s)
      description: What term(s) already in the nfdi4pso ontology should this new term be under? Please list them here, including accession numbers
      required: true

  - type: textarea
    id: Linked terms- Child
    attributes:
      label: Child term(s)
      description: Are there terms already in the nfdi4pso ontology that should be linked underneath the new term? Please list them here, including accession numbers
    validations:
      required: false

- type: textarea
    id: Linked terms- xref
    attributes:
      label: Cross-references
      description: Are there terms in an ontology already imported to SWATE that should be linked to the new term? Please list them here, including the accession number and a link to the term
    validations:
      required: false

  - type: input
    id: attribution
    attributes:
      label: Your ORCID ID
      required: false
